const fs = require('fs');

const batch4 = [
  {
    "id": "jim_corbett",
    "name": "Jim Corbett National Park",
    "description": "Jim Corbett is India's oldest and most famous national park, established in 1936 and the flagship of Project Tiger. The Ramganga River flows through its sal forests, grasslands and river-side terrains, creating a diverse habitat. It holds one of the highest densities of Bengal tigers in India.",
    "shortPitch": "Established in 1936, Jim Corbett is India's oldest and most celebrated national park, serving as the pioneering flagship of Project Tiger. Its diverse landscape of sal forests and the Ramganga River provides thrilling safari experiences and incredible wildlife encounters.",
    "topHighlights": [
      "Thrilling tiger safaris in the Dhikala and Bijrani zones",
      "Birdwatching along the Ramganga River",
      "Overnight stays in exclusive forest lodges under the stars"
    ],
    "region": "North",
    "vibeTags": ["Wildlife", "Nature", "Adventure"],
    "idealSeason": "Nov–May",
    "landscapes": ["Wildlife & Safaris", "Mountains"],
    "peakMonths": [11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [10, 6],
    "avoidMonths": [7, 8, 9],
    "closedMonths": [7, 8, 9],
    "minRequiredDays": 3,
    "latitude": 29.53,
    "longitude": 78.7747,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "ranthambore",
    "name": "Ranthambore National Park",
    "description": "Ranthambore is India's most famous tiger reserve, where tigers are relatively habituated to vehicles — making it one of the best places in Asia for tiger photography. The dramatic backdrop of the 10th-century Ranthambore Fort rising above the jungle adds a unique historical dimension to wildlife safaris.",
    "shortPitch": "Set against the dramatic backdrop of a 10th-century fort, Ranthambore is renowned for its habituated tigers, making it Asia's premier destination for wildlife photography. It offers an unparalleled blend of ancient history and thrilling jungle safaris.",
    "topHighlights": [
      "Unforgettable tiger sightings in an open jeep or canter",
      "Exploring the ancient, UNESCO-listed Ranthambore Fort inside the park",
      "Spotting crocodiles and birds at Padam Talao lake"
    ],
    "region": "West",
    "vibeTags": ["Wildlife", "Historic", "Thrilling"],
    "idealSeason": "Oct–May",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [4, 5, 6],
    "avoidMonths": [7, 8, 9],
    "closedMonths": [7, 8, 9],
    "minRequiredDays": 2,
    "latitude": 26.0173,
    "longitude": 76.5026,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "kaziranga",
    "name": "Kaziranga National Park",
    "description": "Kaziranga is a UNESCO World Heritage Site holding two-thirds of the world's endangered one-horned rhinoceros population. Its vast floodplain grasslands along the Brahmaputra River also shelter the highest density of tigers in any protected area in the world, alongside wild elephants, water buffalo and swamp deer.",
    "shortPitch": "This UNESCO World Heritage Site is a vast floodplain along the Brahmaputra River, proudly sheltering two-thirds of the world's endangered one-horned rhinos. It promises an extraordinary safari experience with incredible densities of tigers, elephants, and unique endemic species.",
    "topHighlights": [
      "Spotting the majestic one-horned rhinoceros on jeep safaris",
      "Early morning elephant safaris through the tall grasslands",
      "Boat safaris along the Brahmaputra spotting diverse birdlife"
    ],
    "region": "Northeast",
    "vibeTags": ["Wildlife", "UNESCO", "Unique"],
    "idealSeason": "Nov–Apr",
    "landscapes": ["Wildlife & Safaris", "Northeast & Living Roots"],
    "peakMonths": [11, 12, 1, 2, 3, 4],
    "shoulderMonths": [10, 5],
    "avoidMonths": [6, 7, 8, 9],
    "closedMonths": [6, 7, 8, 9],
    "minRequiredDays": 3,
    "latitude": 26.5775,
    "longitude": 93.1711,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "bandhavgarh",
    "name": "Bandhavgarh National Park",
    "description": "Bandhavgarh has one of the highest densities of Bengal tigers in India and is consistently rated among the best parks for tiger sightings. The ancient Bandhavgarh Fort with its giant reclining Vishnu statue adds an archaeological dimension to the wildlife experience.",
    "shortPitch": "Boasting one of India's highest Bengal tiger densities, Bandhavgarh consistently offers some of the best big cat sightings in the world. The experience is elevated by ancient cave temples and a majestic fort hidden deep within the lush jungle.",
    "topHighlights": [
      "Exceptional tiger tracking safaris in the Tala zone",
      "Discovering the ancient Bandhavgarh Fort and cave shrines",
      "Searching for leopards, sloth bears, and rich birdlife"
    ],
    "region": "Central",
    "vibeTags": ["Wildlife", "Mystical", "Thrilling"],
    "idealSeason": "Oct–Jun",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5, 6],
    "shoulderMonths": [],
    "avoidMonths": [7, 8, 9],
    "closedMonths": [7, 8, 9],
    "minRequiredDays": 3,
    "latitude": 23.7225,
    "longitude": 81.0245,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "kanha",
    "name": "Kanha National Park",
    "description": "Kanha inspired Rudyard Kipling's 'The Jungle Book' and remains one of India's finest wildlife sanctuaries. Its vast meadows (maidans) dotted with sal and bamboo forests are prime tiger country, while Kanha is also credited with saving the barasingha (swamp deer) from extinction.",
    "shortPitch": "The majestic inspiration behind 'The Jungle Book', Kanha's sprawling meadows and dense sal forests are a quintessential Indian wildlife experience. It is a premier tiger habitat and famously the last stronghold of the rare barasingha swamp deer.",
    "topHighlights": [
      "Tiger and barasingha spotting in the iconic Kanha meadows",
      "Witnessing stunning sunsets from the Bamni Dadar viewpoint",
      "Immersing in the real-life landscapes of 'The Jungle Book'"
    ],
    "region": "Central",
    "vibeTags": ["Wildlife", "Kipling", "Scenic"],
    "idealSeason": "Oct–Jun",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5, 6],
    "shoulderMonths": [],
    "avoidMonths": [7, 8, 9],
    "closedMonths": [7, 8, 9],
    "minRequiredDays": 3,
    "latitude": 22.3345,
    "longitude": 80.6115,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "pench",
    "name": "Pench National Park",
    "description": "Pench — another Jungle Book landscape — straddles Madhya Pradesh and Maharashtra, offering superb wildlife in less crowded conditions than Kanha or Bandhavgarh. It is famous for its leopards, wild dogs, and the tiger named 'Collarwali' — one of the most prolific and studied tigresses in India.",
    "shortPitch": "Straddling two states, Pench offers incredible, less-crowded wildlife safaris through teak forests immortalized in Kipling's tales. It is celebrated for its thriving populations of leopards, wild dogs, and legendary tigers.",
    "topHighlights": [
      "Tracking tigers and elusive leopards on guided jeep safaris",
      "Scenic boat safaris along the peaceful Pench River",
      "Observing wild dog packs in their natural habitat"
    ],
    "region": "Central",
    "vibeTags": ["Wildlife", "Peaceful", "Kipling"],
    "idealSeason": "Oct–Jun",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5, 6],
    "shoulderMonths": [],
    "avoidMonths": [7, 8, 9],
    "closedMonths": [7, 8, 9],
    "minRequiredDays": 2,
    "latitude": 21.6702,
    "longitude": 79.3364,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "tadoba",
    "name": "Tadoba-Andhari Tiger Reserve",
    "description": "Tadoba is Maharashtra's oldest and largest national park, gaining fame as a tiger hotspot with excellent sighting rates. Its teak forests, bamboo groves and Tadoba Lake make it visually dramatic, and the resident tigers — including the celebrated Matkasur family — are well studied and habituated.",
    "shortPitch": "Maharashtra's oldest national park is a rising star in Indian wildlife, offering phenomenal tiger sighting rates amidst dramatic teak and bamboo forests. The beautiful Tadoba Lake acts as an oasis for leopards, gaur, and crocodiles.",
    "topHighlights": [
      "Consistent and thrilling tiger sightings on guided safaris",
      "Wildlife viewing by the scenic Tadoba Lake",
      "Spotting Indian bison (gaur) and sloth bears in the dense forests"
    ],
    "region": "Central",
    "vibeTags": ["Wildlife", "Thrilling", "Rugged"],
    "idealSeason": "Oct–Jun",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5, 6],
    "shoulderMonths": [],
    "avoidMonths": [7, 8, 9],
    "closedMonths": [7, 8, 9],
    "minRequiredDays": 2,
    "latitude": 20.2449,
    "longitude": 79.2974,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "gir",
    "name": "Gir Forest National Park",
    "description": "Gir is the last wild habitat of the Asiatic lion — found nowhere else on Earth outside Africa. The park's dry deciduous forests in Saurashtra shelter around 600 lions, plus leopards, hyenas and the largest population of crocodiles in Gujarat. Lion safari is among India's most exclusive wildlife experiences.",
    "shortPitch": "Gir is globally unique as the absolute last refuge on Earth for the majestic Asiatic lion. Its dry deciduous forests offer an incredibly exclusive safari experience, alongside rich populations of leopards, hyenas, and crocodiles.",
    "topHighlights": [
      "Exclusive open-jeep safaris to spot the rare Asiatic lion",
      "Birdwatching and wildlife photography in dry deciduous forests",
      "Spotting marsh crocodiles at Kamleshwar Dam"
    ],
    "region": "West",
    "vibeTags": ["Wildlife", "Unique", "Exclusive"],
    "idealSeason": "Oct–May",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [],
    "avoidMonths": [6, 7, 8, 9],
    "closedMonths": [6, 7, 8, 9],
    "minRequiredDays": 2,
    "latitude": 21.1243,
    "longitude": 70.8242,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "sundarbans",
    "name": "Sundarbans",
    "description": "The Sundarbans is the world's largest mangrove forest (10,000 sq km) and a UNESCO World Heritage Site, straddling India and Bangladesh. It is the only place in the world where Bengal tigers live in a mangrove tidal delta ecosystem — these 'swimming tigers' are uniquely adapted to the saltwater environment.",
    "shortPitch": "The world's largest mangrove forest is a mystical UNESCO World Heritage Site, famous for its elusive, swimming Bengal tigers. Exploring its intricate tidal waterways by boat offers a hauntingly beautiful and totally unique wildlife experience.",
    "topHighlights": [
      "Boat safaris through winding, mysterious mangrove creeks",
      "Seeking the legendary 'swimming tigers' from watchtowers",
      "Experiencing the Dobsonki Camp canopy walk"
    ],
    "region": "East",
    "vibeTags": ["Wildlife", "Mysterious", "UNESCO"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Wildlife & Safaris"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 21.9497,
    "longitude": 89.1833,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "nagarhole_bandipur",
    "name": "Nagarhole & Bandipur (Nilgiri Biosphere)",
    "description": "Nagarhole (Rajiv Gandhi National Park) and adjacent Bandipur together form the core of the Nilgiri Biosphere Reserve — India's largest tiger conservation area. The contiguous forests here hold the highest concentration of Asian elephants in the world, alongside tigers, leopards and the endemic Nilgiri tahr.",
    "shortPitch": "Forming the heart of the Nilgiri Biosphere, these contiguous forests hold the world's highest concentration of Asian elephants. The lush landscape, framed by the Kabini River, provides world-class sightings of tigers, leopards, and wild dog packs.",
    "topHighlights": [
      "Witnessing massive herds of Asian elephants on safari",
      "Sunset boat rides and wildlife viewing on the Kabini River",
      "Luxury stays at eco-lodges beneath the starry forest sky"
    ],
    "region": "South",
    "vibeTags": ["Wildlife", "Lush", "Luxury"],
    "idealSeason": "Oct–May",
    "landscapes": ["Wildlife & Safaris", "Tea Plantations & Valleys"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [6, 9],
    "avoidMonths": [7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 11.9774,
    "longitude": 76.1362,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "periyar",
    "name": "Periyar Tiger Reserve",
    "description": "Periyar, in the heart of Thekkady's spice hills, is one of India's most accessible and scenic wildlife reserves. Boat rides on the Periyar Lake offer relaxed wildlife watching — herds of elephants, sambar deer and otters come to the water's edge — while the surrounding tea and cardamom estates perfume the air.",
    "shortPitch": "Nestled in Kerala's fragrant spice hills, Periyar offers exceptionally scenic and relaxed wildlife viewing from the waters of its central lake. It is a haven for elephant herds, lush nature walks, and nearby aromatic cardamom estates.",
    "topHighlights": [
      "Relaxing boat safaris on Periyar Lake watching wild elephants",
      "Bamboo rafting and guided tribal border hikes",
      "Exploring the nearby vibrant Kumily spice markets"
    ],
    "region": "South",
    "vibeTags": ["Wildlife", "Scenic", "Spiritual"],
    "idealSeason": "Sep–Apr",
    "landscapes": ["Wildlife & Safaris", "Tea Plantations & Valleys"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3, 4],
    "shoulderMonths": [5, 8],
    "avoidMonths": [6, 7],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 9.4679,
    "longitude": 77.1433,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "munnar",
    "name": "Munnar",
    "description": "Munnar is Kerala's premier hill station, its valleys blanketed in endless rolling tea estates at 1,600 m. The rare Neelakurinji flower — which blooms only once every 12 years, turning the hillsides purple — is Munnar's most celebrated natural phenomenon. Misty mornings, wildlife and cardamom forests add to its appeal.",
    "shortPitch": "Kerala's premier hill station is a breathtaking canvas of endless rolling tea estates wrapped in cool mountain mists. It offers serene plantation walks, spectacular viewpoints, and tranquil escapes into high-altitude nature.",
    "topHighlights": [
      "Driving through endless, meticulously manicured tea plantations",
      "Spotting the endangered Nilgiri tahr at Eravikulam National Park",
      "Enjoying panoramic views from Top Station and Echo Point"
    ],
    "region": "South",
    "vibeTags": ["Serene", "Lush", "Romantic"],
    "idealSeason": "Sep–Mar",
    "landscapes": ["Tea Plantations & Valleys", "Mountains"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3],
    "shoulderMonths": [4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 10.0889,
    "longitude": 77.0595,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "darjeeling",
    "name": "Darjeeling",
    "description": "Darjeeling, at 2,042 m in the Eastern Himalayas, is synonymous with the world's finest teas. The Toy Train (UNESCO World Heritage), views of the Kanchenjunga, colonial-era clubs and the famous sunrise from Tiger Hill make it India's most beloved hill station. Darjeeling's FTGFOP1 first-flush teas are liquid gold.",
    "shortPitch": "Synonymous with the world's finest teas, Darjeeling is a timeless Himalayan retreat offering majestic views of Mount Kanchenjunga. The vintage UNESCO Toy Train and colonial-era charm make it deeply nostalgic and romantic.",
    "topHighlights": [
      "Watching the sunrise over Kanchenjunga from Tiger Hill",
      "Riding the historic UNESCO Darjeeling Himalayan Railway",
      "Touring legendary tea estates and tasting first-flush brews"
    ],
    "region": "East",
    "vibeTags": ["Nostalgic", "Scenic", "Romantic"],
    "idealSeason": "Oct–May",
    "landscapes": ["Tea Plantations & Valleys", "Mountains"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [9],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 27.036,
    "longitude": 88.2627,
    "requiresAcclimatization": true,
    "isHub": true
  },
  {
    "id": "ooty",
    "name": "Ooty (Udhagamandalam)",
    "description": "Ooty is the 'Queen of Hill Stations' — the most famous hill resort in South India. The Nilgiri Mountain Railway (Toy Train) UNESCO heritage line, botanical gardens, the Ooty Lake and surrounding eucalyptus and tea estates have drawn visitors since the British Raj.",
    "shortPitch": "The undisputed 'Queen of Hill Stations', Ooty enchants with its sprawling botanical gardens, scenic lakes, and crisp eucalyptus air. The nostalgic ride on its UNESCO-listed mountain railway remains a quintessential Indian experience.",
    "topHighlights": [
      "Riding the UNESCO Nilgiri Mountain Railway toy train",
      "Strolling through the meticulously maintained Ooty Botanical Gardens",
      "Boating on the serene waters of Ooty Lake"
    ],
    "region": "South",
    "vibeTags": ["Colonial", "Nostalgic", "Lush"],
    "idealSeason": "Oct–Jun",
    "landscapes": ["Tea Plantations & Valleys", "Mountains"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5, 6],
    "shoulderMonths": [9],
    "avoidMonths": [7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 11.4064,
    "longitude": 76.6932,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "coonoor",
    "name": "Coonoor",
    "description": "Coonoor is quieter and less crowded than Ooty but equally beautiful, with terraced tea gardens cascading down the Nilgiri slopes. Sim's Park is a magnificent botanical garden, and the town serves as the main gateway for the Nilgiri Mountain Railway experience between Mettupalayam and Ooty.",
    "shortPitch": "A quieter, more intimate neighbor to Ooty, Coonoor features breathtaking terraced tea gardens cascading down the Nilgiri hills. It offers stunning viewpoints, peaceful botanical parks, and a slower, deeply relaxing pace of life.",
    "topHighlights": [
      "Wandering through the rare flora at Sim's Park",
      "Taking in valley panoramas from Dolphin's Nose viewpoint",
      "Enjoying peaceful drives through cascading tea estates"
    ],
    "region": "South",
    "vibeTags": ["Peaceful", "Lush", "Scenic"],
    "idealSeason": "Oct–Jun",
    "landscapes": ["Tea Plantations & Valleys", "Mountains"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5, 6],
    "shoulderMonths": [9],
    "avoidMonths": [7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 11.353,
    "longitude": 76.7959,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "wayanad",
    "name": "Wayanad",
    "description": "Wayanad is a lush highland district in Kerala's northern Western Ghats, blanketed with coffee, tea and spice plantations interspersed with tribal villages and wildlife corridors. Edakkal Caves contain Neolithic petroglyphs over 6,000 years old, while Chembra Peak's heart-shaped lake is a trekking icon.",
    "shortPitch": "Nestled in the Western Ghats, Wayanad is a pristine highland woven with coffee, tea, and spice plantations. It seamlessly blends ancient history, vibrant tribal culture, and stunning nature treks into one lush escape.",
    "topHighlights": [
      "Discovering ancient Neolithic rock carvings at Edakkal Caves",
      "Trekking to the iconic heart-shaped lake at Chembra Peak",
      "Wildlife spotting at the Wayanad Wildlife Sanctuary"
    ],
    "region": "South",
    "vibeTags": ["Lush", "Ancient", "Adventure"],
    "idealSeason": "Oct–May",
    "landscapes": ["Tea Plantations & Valleys", "Wildlife & Safaris", "Mountains"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [9],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 11.6854,
    "longitude": 76.132,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "delhi",
    "name": "Delhi",
    "description": "Delhi, India's capital, layers 3,000 years of history from the Mughal Empire to the modern Republic. Old Delhi's lanes around the Red Fort and Jama Masjid contrast sharply with Lutyens' Delhi's grand colonial boulevards and New Delhi's diplomatic enclaves. It is the gateway for millions of international travellers.",
    "shortPitch": "India's pulsing capital perfectly bridges the ancient and the modern, layering 3,000 years of history alongside cutting-edge culture. From the chaotic charm of Old Delhi to grand colonial boulevards, it is a city of extraordinary depth.",
    "topHighlights": [
      "Exploring UNESCO heritage at the Red Fort and Qutub Minar",
      "Navigating the vibrant, spice-scented lanes of Chandni Chowk",
      "Admiring the Mughal architectural perfection of Humayun's Tomb"
    ],
    "region": "North",
    "vibeTags": ["Historic", "Vibrant", "Cosmopolitan"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Vibrant Metropolises", "Royal Cities", "Spirituality & Ghats"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 28.6139,
    "longitude": 77.209,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "mumbai",
    "name": "Mumbai",
    "description": "Mumbai — the 'City of Dreams' — is India's financial capital, Bollywood's home and a city of extraordinary contrasts. Its Gothic colonial architecture, Art Deco seafront, island forts, bustling street food and Asia's largest slum Dharavi sit alongside luxury neighbourhoods and one of the world's most vibrant arts scenes.",
    "shortPitch": "The relentless 'City of Dreams' is India's financial and entertainment powerhouse, offering a dizzying mix of Bollywood glamour and street-level grit. Its stunning Gothic architecture and seaside promenades define its iconic coastal skyline.",
    "topHighlights": [
      "Strolling the seafront promenade of Marine Drive at sunset",
      "Marveling at the Gateway of India and taking a ferry to Elephanta Caves",
      "Taking an insightful, community-led walking tour of Dharavi"
    ],
    "region": "West",
    "vibeTags": ["Dynamic", "Cinematic", "Cosmopolitan"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Vibrant Metropolises", "Coastal & Islands"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [4, 5],
    "avoidMonths": [6, 7, 8, 9],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 19.076,
    "longitude": 72.8777,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "bengaluru",
    "name": "Bengaluru (Bangalore)",
    "description": "Bengaluru is India's Silicon Valley and the fastest-growing major city in Asia. Known for its pleasant climate, startup culture, craft beer scene, colonial parks and vibrant arts communities, it is the modern face of India's economic rise — a cosmopolitan city that blends technology, tradition and progressive culture.",
    "shortPitch": "India's thriving Silicon Valley blends cutting-edge startup culture with magnificent colonial parks and a world-class craft beer scene. Blessed with a perpetually pleasant climate, it is the progressive, modern face of the nation.",
    "topHighlights": [
      "Relaxing among ancient trees in Lalbagh Botanical Garden",
      "Exploring the city's famous craft brewery and nightlife scene",
      "Visiting the majestic, Tudor-style Bengaluru Palace"
    ],
    "region": "South",
    "vibeTags": ["Modern", "Dynamic", "Cosmopolitan"],
    "idealSeason": "Sep–May",
    "landscapes": ["Vibrant Metropolises"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [6, 7, 8],
    "avoidMonths": [],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 12.9716,
    "longitude": 77.5946,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "kolkata",
    "name": "Kolkata",
    "description": "Kolkata — the 'City of Joy' and former British capital of India — is the cultural and intellectual heart of the nation. Its crumbling colonial grandeur, world-class art scene, Durga Puja festival, hand-pulled rickshaws, Tagore's Rabindranath heritage and legendary Bengali cuisine make it one of India's most richly textured cities.",
    "shortPitch": "The former British capital remains India's profound intellectual and cultural heart, radiating old-world colonial grandeur. Famous for its literary heritage and legendary street food, Kolkata is a deeply soulful and textured 'City of Joy'.",
    "topHighlights": [
      "Admiring the imposing marble grandeur of the Victoria Memorial",
      "Crossing the iconic Howrah Bridge over the Hooghly River",
      "Experiencing the unparalleled energy of the Durga Puja festival"
    ],
    "region": "East",
    "vibeTags": ["Cultural", "Nostalgic", "Soulful"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Vibrant Metropolises"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9],
    "avoidMonths": [4, 5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 22.5726,
    "longitude": 88.3639,
    "requiresAcclimatization": false,
    "isHub": true
  }
];

const existingData = JSON.parse(fs.readFileSync('prisma/data.json', 'utf8'));
const merged = [...existingData, ...batch4];
fs.writeFileSync('prisma/data.json', JSON.stringify(merged, null, 2));

console.log('Appended batch 4.');
