const fs = require('fs');
const data = JSON.parse(fs.readFileSync('prisma/data.json', 'utf8'));

const batch2 = [
  {
    "id": "sonamarg",
    "name": "Sonamarg",
    "description": "Sonamarg — 'Meadow of Gold' — lies at 2,730 m on the old Silk Road and serves as the gateway to Ladakh. Its glaciers, rivers and flower-strewn meadows are spectacular in summer, while it becomes a snow wonderland in winter. The Thajiwas Glacier is easily accessible and enormously popular.",
    "shortPitch": "Known as the 'Meadow of Gold', Sonamarg lies on the ancient Silk Road serving as the stunning alpine gateway to Ladakh. Its flower-strewn meadows and dramatic glaciers transform into a pristine snow wonderland during the winter.",
    "topHighlights": [
      "Thajiwas Glacier treks and sled rides",
      "Gateway to the high-altitude Vishansar & Krishansar Lakes",
      "Crossing the legendary Zoji La Pass"
    ],
    "region": "North",
    "vibeTags": ["Scenic", "Peaceful", "Pristine"],
    "idealSeason": "Apr–Oct",
    "landscapes": ["Mountains"],
    "peakMonths": [4, 5, 6, 7, 8, 9, 10],
    "shoulderMonths": [3, 11],
    "avoidMonths": [12, 1, 2],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 34.3005,
    "longitude": 75.2952,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "tawang",
    "name": "Tawang",
    "description": "Tawang is home to the 400-year-old Tawang Monastery — the largest in India and the second-largest in the world after Lhasa — perched at 3,048 m with breathtaking views of the Himalayan ranges. The town is also significant as the birthplace of the 6th Dalai Lama and a living example of Tibetan Buddhist culture on Indian soil.",
    "shortPitch": "Perched at 3,048m, Tawang is a deeply spiritual frontier town home to India's largest and the world's second-largest Tibetan Buddhist monastery. It offers breathtaking Himalayan vistas and stands as a living testament to vibrant Tibetan culture on Indian soil.",
    "topHighlights": [
      "The majestic 400-year-old Tawang Monastery",
      "Crossing the dramatic Sela Pass and Sela Lake",
      "Exploring the historic Bum La Pass at the India-China border"
    ],
    "region": "East",
    "vibeTags": ["Spiritual", "Remote", "Cultural"],
    "idealSeason": "Mar–Oct",
    "landscapes": ["Mountains", "Spiritual India", "Hidden Villages"],
    "peakMonths": [3, 4, 5, 9, 10],
    "shoulderMonths": [6, 7, 8],
    "avoidMonths": [11, 12, 1, 2],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 27.5861,
    "longitude": 91.8594,
    "requiresAcclimatization": true,
    "isHub": false
  },
  {
    "id": "ziro-valley",
    "name": "Ziro Valley",
    "description": "Ziro is a UNESCO World Heritage-listed valley renowned for its terraced paddy fields, pine hills and the unique Apatani tribal culture. The annual Ziro Music Festival draws indie music lovers from across Asia, making it India's most atmospheric open-air music event, set against a backdrop of misty mountains.",
    "shortPitch": "Ziro Valley is a UNESCO-listed haven renowned for its terraced paddy fields, mist-covered pine hills, and the unique Apatani tribal culture. Every September, it transforms into Asia's most atmospheric indie music destination with the renowned Ziro Music Festival.",
    "topHighlights": [
      "Immersive experiences with the indigenous Apatani tribe",
      "The spectacular outdoor Ziro Music Festival (September)",
      "Trekking in the Talley Valley Wildlife Sanctuary"
    ],
    "region": "East",
    "vibeTags": ["Tribal", "Cultural", "Scenic"],
    "idealSeason": "Mar–Oct",
    "landscapes": ["Mountains", "Hidden Villages"],
    "peakMonths": [3, 4, 5, 9, 10],
    "shoulderMonths": [6, 7, 8],
    "avoidMonths": [11, 12, 1, 2],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 27.5562,
    "longitude": 93.8340,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "gangtok",
    "name": "Gangtok",
    "description": "The capital of Sikkim, Gangtok is a vibrant hill city with Kanchenjunga — the world's third-highest peak — as its backdrop. It serves as the gateway to North Sikkim's remote high-altitude lakes, the revered Rumtek Monastery and the many trekking routes that wind through the Eastern Himalayas.",
    "shortPitch": "Gangtok is the vibrant capital of Sikkim, perched dramatically with sweeping views of Kanchenjunga, the world's third-highest peak. It perfectly balances a thriving mountain-city culture with access to deep Eastern Himalayan treks and revered monasteries.",
    "topHighlights": [
      "The stunning high-altitude Tsomgo (Changu) Lake",
      "Visits to the revered Rumtek Monastery",
      "Nathula Pass at the historic India-China border"
    ],
    "region": "East",
    "vibeTags": ["Scenic", "Cultural", "Bustling"],
    "idealSeason": "Sep–Jun",
    "landscapes": ["Mountains", "Spiritual India"],
    "peakMonths": [3, 4, 5, 9, 10, 11],
    "shoulderMonths": [12, 1, 2, 6],
    "avoidMonths": [7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 27.3389,
    "longitude": 88.6065,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "pelling-yuksom",
    "name": "Pelling & Yuksom",
    "description": "Pelling offers one of India's finest views of the Kanchenjunga massif, especially at dawn when the sunrise turns the snow peaks golden. Yuksom, the historic first capital of Sikkim, is the starting point for the classic Goecha La trek to the base of Kanchenjunga.",
    "shortPitch": "Pelling offers arguably the finest dawn views of the Kanchenjunga massif in all of India. Nearby, the historic village of Yuksom serves as the rugged starting point for the iconic Goecha La trek.",
    "topHighlights": [
      "Unmatched sunrise views over Kanchenjunga",
      "The 350-year-old Pemayangtse Monastery",
      "Trekking to the sacred Khecheopalri Lake"
    ],
    "region": "East",
    "vibeTags": ["Scenic", "Peaceful", "Spiritual"],
    "idealSeason": "Sep–May",
    "landscapes": ["Mountains", "Spiritual India"],
    "peakMonths": [3, 4, 5, 9, 10, 11],
    "shoulderMonths": [12, 1, 2],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 27.3168,
    "longitude": 88.2384,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "yumthang-valley",
    "name": "Yumthang Valley",
    "description": "Yumthang — the 'Valley of Flowers of Sikkim' — lies at 3,564 m in North Sikkim and blooms with rhododendrons and primulas from March to May. The Zero Point beyond Yumthang at 4,800 m is the last accessible point near the Chinese border, offering spectacular snow and glacier views.",
    "shortPitch": "Known as the 'Valley of Flowers of Sikkim', Yumthang sits at 3,564m and explodes with vibrant rhododendrons every spring. Further up lies Zero Point, a spectacular glacial frontier offering panoramic snowy vistas near the border.",
    "topHighlights": [
      "Rhododendron sanctuary spring blooms (Mar-May)",
      "Glacier views from Zero Point (4,800m)",
      "Natural hot springs amidst alpine terrain"
    ],
    "region": "East",
    "vibeTags": ["Lush", "Pristine", "Remote"],
    "idealSeason": "Mar–May",
    "landscapes": ["Mountains", "Hidden Villages"],
    "peakMonths": [3, 4, 5],
    "shoulderMonths": [10, 11],
    "avoidMonths": [6, 7, 8, 12, 1, 2],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 27.8105,
    "longitude": 88.6946,
    "requiresAcclimatization": true,
    "isHub": false
  },
  {
    "id": "kargil",
    "name": "Kargil",
    "description": "Kargil is the second-largest town in Ladakh, a strategic military hub known worldwide for the 1999 Kargil War. Today it draws history and adventure travellers en route between Leh and Srinagar, with access to remote valleys, ancient cave Buddhist monasteries and the towering Zoji La pass.",
    "shortPitch": "Kargil is a deeply historic military hub set against a backdrop of stark, towering mountain passes. It acts as a rugged stepping stone to remote valleys, ancient cave monasteries, and the breathtaking Zoji La pass.",
    "topHighlights": [
      "Paying respects at the Kargil War Memorial in Dras",
      "Exploring the ancient Mulbekh Monastery rock sculptures",
      "Discovering the remote glaciers of Suru Valley"
    ],
    "region": "North",
    "vibeTags": ["Historic", "Remote", "Raw"],
    "idealSeason": "May–Sep",
    "landscapes": ["Mountains"],
    "peakMonths": [5, 6, 7, 8, 9],
    "shoulderMonths": [4, 10],
    "avoidMonths": [11, 12, 1, 2, 3],
    "closedMonths": [12, 1, 2, 3],
    "minRequiredDays": 2,
    "latitude": 34.5539,
    "longitude": 76.1349,
    "requiresAcclimatization": true,
    "isHub": false
  },
  {
    "id": "kinnaur-valley",
    "name": "Kinnaur Valley",
    "description": "Kinnaur is famed for its apple orchards, terraced vineyards, ancient wooden temples and the stunning confluence of the Sutlej River with Himalayan peaks. The Hindustan–Tibet Highway passes through here, offering dramatic cliff-hanging roads, landslide-prone passes and a transition from Hindu to Buddhist culture.",
    "shortPitch": "Kinnaur Valley is a cultural bridge between Hinduism and Buddhism, famed for its terraced apple orchards and ancient wooden temples. The dramatic Hindustan-Tibet Highway cuts through its cliff-hanging passes, offering an unforgettable adventure.",
    "topHighlights": [
      "Chitkul, the last Indian village on the Indo-Tibet border",
      "The ancient Bhimakali Temple in Sarahan",
      "Spectacular views of the Kinnaur Kailash peak"
    ],
    "region": "North",
    "vibeTags": ["Scenic", "Cultural", "Raw"],
    "idealSeason": "Apr–Oct",
    "landscapes": ["Mountains", "Hidden Villages"],
    "peakMonths": [4, 5, 6, 9, 10],
    "shoulderMonths": [7, 8],
    "avoidMonths": [11, 12, 1, 2, 3],
    "closedMonths": [12, 1, 2],
    "minRequiredDays": 3,
    "latitude": 31.6510,
    "longitude": 78.2618,
    "requiresAcclimatization": true,
    "isHub": false
  },
  {
    "id": "north-goa",
    "name": "North Goa",
    "description": "North Goa is India's most famous beach destination — a heady mix of Portuguese colonial heritage, lively beach shacks, water sports, flea markets and an infectious party scene. Beaches from Calangute to Vagator each have distinct personalities ranging from family-friendly to bohemian.",
    "shortPitch": "North Goa is India's premier coastal playground, offering a heady mix of Portuguese colonial heritage and an infectious party scene. Its legendary beaches feature lively shacks, water sports, and iconic flea markets.",
    "topHighlights": [
      "Vibrant nightlife and the Anjuna Flea Market",
      "Water sports at Baga and Calangute beaches",
      "Sunset views from the cliff-top Fort Aguada and Chapora Fort"
    ],
    "region": "West",
    "vibeTags": ["Vibrant", "Bohemian", "Fast-paced"],
    "idealSeason": "Nov–Mar",
    "landscapes": ["Beaches", "Modern Cities"],
    "peakMonths": [11, 12, 1, 2, 3],
    "shoulderMonths": [10, 4, 5],
    "avoidMonths": [6, 7, 8, 9],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 15.5937,
    "longitude": 73.7402,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "south-goa",
    "name": "South Goa",
    "description": "South Goa is quieter and more upscale than the north, with long empty stretches of white sand, luxury resorts, ancient spice plantations and the old Portuguese capital of Margao. Palolem's crescent-shaped bay and Agonda's pristine sands are among India's most beautiful beaches.",
    "shortPitch": "Quieter and more upscale than its northern counterpart, South Goa boasts long, empty stretches of pristine white sand and luxury resorts. It is a tranquil retreat surrounded by ancient spice plantations and grand Portuguese cathedrals.",
    "topHighlights": [
      "The stunning crescent-shaped bay of Palolem Beach",
      "UNESCO-listed churches and basilicas of Old Goa",
      "Day trips to the majestic Dudhsagar Waterfalls"
    ],
    "region": "West",
    "vibeTags": ["Relaxed", "Luxury", "Romantic"],
    "idealSeason": "Nov–Mar",
    "landscapes": ["Beaches", "Hidden Villages"],
    "peakMonths": [11, 12, 1, 2, 3],
    "shoulderMonths": [10, 4, 5],
    "avoidMonths": [6, 7, 8, 9],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 15.2736,
    "longitude": 73.9663,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "gokarna",
    "name": "Gokarna",
    "description": "Gokarna is a small temple town on the Karnataka coast that has evolved into a beloved backpacker beach destination. The pristine Om Beach — shaped like the Om symbol — and the quieter Half Moon and Paradise beaches attract travellers seeking a more authentic alternative to Goa, while the Mahabaleshwar Temple draws Hindu pilgrims.",
    "shortPitch": "Gokarna is a deeply spiritual coastal temple town that has evolved into a beloved, laid-back backpacker haven. Its pristine, symbol-shaped beaches offer a quieter, highly authentic alternative to the bustle of Goa.",
    "topHighlights": [
      "Beach-hopping between Om, Half Moon, and Paradise beaches",
      "Pilgrimage to the ancient Mahabaleshwar Temple",
      "Serene sunset viewpoints from the Gokarna Fort cliffs"
    ],
    "region": "South",
    "vibeTags": ["Bohemian", "Spiritual", "Peaceful"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Beaches", "Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 14.5398,
    "longitude": 74.3180,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "andaman-islands",
    "name": "Andaman Islands",
    "description": "The Andaman Islands are India's premier tropical island destination, boasting some of Asia's finest snorkelling and diving over pristine coral reefs. Port Blair is the gateway, while Havelock (Swaraj Dweep) and Neil (Shaheed Dweep) islands offer luminescent beaches of global renown.",
    "shortPitch": "The Andaman Islands stand as India's premier tropical archipelago, boasting luminescent white-sand beaches and world-class scuba diving. Its pristine coral reefs and dense mangrove forests create an unparalleled oceanic escape.",
    "topHighlights": [
      "Relaxing on Radhanagar Beach, consistently rated Asia's best",
      "Scuba diving over pristine coral reefs at Havelock and Neil Islands",
      "Historical tours of the Cellular Jail National Memorial"
    ],
    "region": "Islands",
    "vibeTags": ["Tropical", "Pristine", "Romantic"],
    "idealSeason": "Oct–May",
    "landscapes": ["Islands", "Beaches"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [9],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 6,
    "latitude": 11.9761,
    "longitude": 92.9876,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "lakshadweep",
    "name": "Lakshadweep",
    "description": "India's only coral atoll archipelago in the Arabian Sea, Lakshadweep's 36 islands offer crystal-clear lagoons, vibrant coral reefs and an almost untouched marine ecosystem. Strict visitor limits have kept it remarkably pristine. Agatti Island has the main airport; Bangaram is a luxury resort island.",
    "shortPitch": "As India's only coral atoll archipelago, Lakshadweep offers a hyper-exclusive island escape with crystal-clear lagoons and an untouched marine ecosystem. Strict visitor limits have preserved its staggering natural beauty.",
    "topHighlights": [
      "Snorkelling and scuba diving in vibrant, untouched coral reefs",
      "Luxury stays on the secluded Bangaram Island",
      "Glass-bottom boat rides in the turquoise Agatti lagoon"
    ],
    "region": "Islands",
    "vibeTags": ["Pristine", "Exclusive", "Remote"],
    "idealSeason": "Oct–May",
    "landscapes": ["Islands", "Beaches"],
    "peakMonths": [10, 11, 12, 1, 2, 3, 4, 5],
    "shoulderMonths": [9],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 4,
    "latitude": 10.5667,
    "longitude": 72.6417,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "varkala",
    "name": "Varkala",
    "description": "Varkala is famous for its dramatic red cliffs dropping onto a golden beach — a setting unlike anywhere else in India. The clifftop North Cliff promenade is lined with yoga studios, Ayurveda centres, and beach restaurants. The ancient Janardhana Swami Temple adds a spiritual dimension to this unique coastal destination.",
    "shortPitch": "Varkala is visually dramatic, famous for its towering red cliffs that drop sheer into the Arabian Sea. It is a soulful coastal retreat blending clifftop yoga, Ayurvedic healing, and ancient temple spirituality.",
    "topHighlights": [
      "Sunset views from the bustling North Cliff promenade",
      "Ayurveda wellness retreats and beachfront yoga",
      "Visiting the ancient Janardhana Swami Temple"
    ],
    "region": "South",
    "vibeTags": ["Soulful", "Bohemian", "Relaxed"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Beaches", "Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 8.7338,
    "longitude": 76.7059,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "kovalam",
    "name": "Kovalam",
    "description": "Kovalam, near Thiruvananthapuram, is Kerala's most developed beach resort town with a crescent of linked beaches known as Lighthouse Beach, Hawa Beach and Samudra Beach. It is the Ayurveda capital of Kerala's coast, drawing thousands annually for traditional Keralan massage and healing treatments.",
    "shortPitch": "Kovalam is Kerala's premier coastal resort, defined by its iconic crescent of linked beaches and towering lighthouse. It stands globally recognized as a restorative capital for traditional Ayurvedic massage and holistic healing.",
    "topHighlights": [
      "Relaxing at the iconic crescent-shaped Lighthouse Beach",
      "World-class traditional Ayurvedic healing treatments",
      "Exploring the nearby Vizhinjam Fishing Harbour"
    ],
    "region": "South",
    "vibeTags": ["Relaxed", "Restorative", "Soulful"],
    "idealSeason": "Sep–Mar",
    "landscapes": ["Beaches"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3],
    "shoulderMonths": [8, 4, 5],
    "avoidMonths": [6, 7],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 8.4004,
    "longitude": 76.9787,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "karwar-dandeli",
    "name": "Karwar & Dandeli",
    "description": "Karwar is a pristine harbour town at the mouth of the Kali River on the northern Karnataka coast, offering unspoilt beaches largely untouched by mass tourism. Inland, Dandeli is Karnataka's adventure capital — a tiger reserve and white-water rafting hotspot on the Western Ghats rivers.",
    "shortPitch": "Combining untouched coastal beauty with deep forest adventure, this twin destination offers the best of both worlds. Enjoy pristine harbour beaches in Karwar before heading inland to Dandeli for white-water rafting and tiger safaris.",
    "topHighlights": [
      "White-water rafting on the Kali River in Dandeli",
      "Wildlife safaris spotting elusive black panthers",
      "Unspoiled beach retreats at Devbagh and Kurumgad Island"
    ],
    "region": "South",
    "vibeTags": ["Raw", "Pristine", "Exhilarating"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Beaches", "Wildlife & Jungle"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 14.8048,
    "longitude": 74.1333,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "tarkarli-sindhudurg",
    "name": "Tarkarli & Sindhudurg",
    "description": "Tarkarli on the Konkan coast is famous for the clearest waters in Maharashtra, excellent for scuba diving and snorkelling. The offshore Sindhudurg Fort — built by Chhatrapati Shivaji Maharaj — sits on a rocky island in the sea, accessible by boat, and is one of the finest sea forts in Asia.",
    "shortPitch": "Tarkarli boasts the clearest waters on the Konkan coast, making it a spectacular hub for scuba diving and snorkelling. Just offshore lies Sindhudurg Fort, a magnificent 17th-century sea fortress built on a rocky island.",
    "topHighlights": [
      "Scuba diving and snorkelling in crystal-clear coastal waters",
      "Boat trips to explore the historic offshore Sindhudurg Fort",
      "Savouring authentic, spicy Konkan seafood cuisine"
    ],
    "region": "West",
    "vibeTags": ["Pristine", "Historic", "Scenic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Beaches", "Hidden Villages"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 16.0401,
    "longitude": 73.4839,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "ratnagiri",
    "name": "Ratnagiri",
    "description": "Ratnagiri on the Konkan coast is the birthplace of Bal Gangadhar Tilak and home to India's most prized Alphonso mangoes. Its red-laterite cliffs, ancient forts, pristine coves and Ganesh ghat make it a scenic and historically rich coastal destination largely undiscovered by international travellers.",
    "shortPitch": "Ratnagiri is an undiscovered gem on the Konkan coast, defined by dramatic red-laterite cliffs and pristine ocean coves. Historically rich, it is also globally renowned as the heartland of the prized Alphonso mango.",
    "topHighlights": [
      "Tours of organic Alphonso mango farms",
      "Exploring Ratnadurg Fort and its historic lighthouse",
      "Discovering the royal Thibaw Palace Museum"
    ],
    "region": "West",
    "vibeTags": ["Authentic", "Quiet", "Historic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Beaches", "Hidden Villages"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 16.9902,
    "longitude": 73.3120,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "jaipur",
    "name": "Jaipur",
    "description": "The 'Pink City', Jaipur is the gateway to Rajasthan and one of India's most visited destinations. Its rose-pink buildings, magnificent forts, Mughal-Rajput palaces and vibrant bazaars combine to make it a UNESCO World Heritage-listed city of extraordinary colour and royal grandeur.",
    "shortPitch": "The famed 'Pink City' is a UNESCO World Heritage marvel of royal grandeur and extraordinary colour. Jaipur enchants visitors with its majestic hilltop forts, opulent Mughal-Rajput palaces, and bustling artisan bazaars.",
    "topHighlights": [
      "The colossal Amber Fort and its intricate Mirror Palace",
      "The iconic, lattice-windowed Hawa Mahal (Palace of Winds)",
      "The astronomical wonders of the Jantar Mantar observatory"
    ],
    "region": "West",
    "vibeTags": ["Regal", "Historic", "Vibrant"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities", "Modern Cities"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 26.9124,
    "longitude": 75.7873,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "udaipur",
    "name": "Udaipur",
    "description": "Udaipur — the 'City of Lakes' — is widely considered India's most romantic city, its white marble palaces reflected in shimmering lakes against the backdrop of the Aravalli Hills. The Lake Palace hotel, appearing to float on Lake Pichola, is among the most photographed buildings in Asia.",
    "shortPitch": "Widely considered India's most romantic destination, Udaipur is a stunning 'City of Lakes' framed by the Aravalli Hills. Its ethereal white marble palaces appear to float magically upon shimmering, serene waters.",
    "topHighlights": [
      "Romantic boat rides across the serene Lake Pichola",
      "Exploring the massive, ornate City Palace complex",
      "Sunset views from the hilltop Sajjangarh (Monsoon Palace)"
    ],
    "region": "West",
    "vibeTags": ["Romantic", "Regal", "Luxury"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 24.5854,
    "longitude": 73.7125,
    "requiresAcclimatization": false,
    "isHub": false
  }
];

data.push(...batch2);
fs.writeFileSync('prisma/data.json', JSON.stringify(data, null, 2));
