const fs = require('fs');
const data = JSON.parse(fs.readFileSync('prisma/data.json', 'utf8'));

const batch3 = [
  {
    "id": "jodhpur",
    "name": "Jodhpur",
    "description": "The 'Blue City', Jodhpur is dominated by the colossal Mehrangarh Fort rising 122 m from a rocky outcrop. The old city below is painted indigo blue, creating an iconic visual unlike any other in India. It serves as the western gateway to the Thar Desert and a hub for desert safaris and textile shopping.",
    "shortPitch": "The famed 'Blue City' of Jodhpur is visually iconic, defined by its sea of indigo houses resting beneath the colossal Mehrangarh Fort. It acts as the majestic western gateway to the Thar Desert, offering a rich tapestry of history and artisanal crafts.",
    "topHighlights": [
      "The colossal Mehrangarh Fort and Museum",
      "Wandering the vibrant Blue City old town",
      "Shopping for spices and textiles at Sardar Market"
    ],
    "region": "West",
    "vibeTags": ["Historic", "Vibrant", "Iconic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities", "Desert"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 26.2389,
    "longitude": 73.0243,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "jaisalmer",
    "name": "Jaisalmer",
    "description": "The 'Golden City', Jaisalmer rises from the Thar Desert like a mirage — its honey-coloured sandstone fort and havelis (merchant mansions) glowing at sunset. It is India's quintessential desert city: camel safaris into the sand dunes of Sam and Khuri, folk music under the stars and intricately carved Jain temples await.",
    "shortPitch": "Rising like a mirage from the Thar Desert, the 'Golden City' of Jaisalmer glows beautifully at sunset from its honey-coloured sandstone fort. It is India's quintessential desert experience, offering starry camel safaris and intricately carved living forts.",
    "topHighlights": [
      "Exploring the UNESCO-listed, living Jaisalmer Fort",
      "Camel safaris through the Sam Sand Dunes",
      "Intricately carved merchant mansions like Patwon Ki Haveli"
    ],
    "region": "West",
    "vibeTags": ["Golden", "Romantic", "Rustic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities", "Desert"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 26.9157,
    "longitude": 70.9083,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "bikaner",
    "name": "Bikaner",
    "description": "Bikaner is a fascinating walled desert city famed for its medieval fort, ornate Jain havelis, camel breeding farm, and the extraordinary Karni Mata Temple (Rat Temple) at Deshnok. It is less touristed than Jaipur or Jodhpur but equally rich in royal architecture and desert heritage.",
    "shortPitch": "Bikaner is a deeply authentic walled desert city boasting exquisite royal architecture and ornate Jain havelis without the heavy crowds. It offers unique cultural sites like a national camel breeding farm and the extraordinary Karni Mata Temple.",
    "topHighlights": [
      "The magnificent Junagarh Fort complex",
      "The extraordinary Karni Mata Rat Temple at Deshnok",
      "Guided camel encounters at the National Research Centre on Camel"
    ],
    "region": "West",
    "vibeTags": ["Historic", "Quiet", "Authentic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities", "Desert"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 28.0229,
    "longitude": 73.3119,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "bundi",
    "name": "Bundi",
    "description": "Bundi is one of Rajasthan's best-kept secrets — a small medieval town with an impossibly photogenic palace covered in Rajput murals, a clifftop fort and step-wells (baoris) of exquisite craftsmanship. Rudyard Kipling lived here and wrote much of 'Kim' in the town. Backpackers adore it for its authenticity.",
    "shortPitch": "One of Rajasthan's best-kept secrets, Bundi is a medieval town renowned for its impossibly photogenic palace, exquisite Rajput murals, and grand step-wells. It retains an unspoiled authenticity that inspired writers like Rudyard Kipling.",
    "topHighlights": [
      "The intricate Chitrashala murals at Bundi Palace",
      "Historic step-wells including the grand Raniji ki Baori",
      "Hikes up to the clifftop Taragarh Fort"
    ],
    "region": "West",
    "vibeTags": ["Hidden", "Romantic", "Authentic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 25.4415,
    "longitude": 75.6385,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "pushkar",
    "name": "Pushkar",
    "description": "Pushkar is one of Hinduism's holiest cities, built around the sacred Pushkar Lake with 52 bathing ghats and the rare Brahma Temple (one of very few in the world). Every November it hosts the Pushkar Camel Fair — the world's largest — a spectacular spectacle of thousands of camels, horses and cattle.",
    "shortPitch": "Built around a deeply sacred lake with 52 bathing ghats, Pushkar is an ancient holy city renowned for its rare Brahma Temple. It is world-famous for its spectacular annual Camel Fair that transforms the desert into a riot of colour and energy.",
    "topHighlights": [
      "Visiting the sacred Brahma Temple",
      "Attending sunset rituals at the Pushkar Lake ghats",
      "Experiencing the vibrant Pushkar Camel Fair (November)"
    ],
    "region": "West",
    "vibeTags": ["Spiritual", "Bohemian", "Vibrant"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities", "Spiritual India", "Desert"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 26.4862,
    "longitude": 74.5513,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "shekhawati",
    "name": "Shekhawati Region",
    "description": "Shekhawati is an open-air gallery of some of the finest painted havelis in the world, created by wealthy merchant families in the 18th–19th centuries. The towns of Mandawa, Nawalgarh, Fatehpur and Ramgarh contain thousands of buildings adorned with extraordinary frescoes — mythological, historical and fantastical.",
    "shortPitch": "Shekhawati is an extraordinary open-air gallery of ornate painted havelis commissioned by wealthy 18th-century merchants. Towns like Mandawa and Nawalgarh are adorned with thousands of vibrant frescoes depicting mythological and historical tales.",
    "topHighlights": [
      "Exploring the painted havelis of Mandawa",
      "The Nawalgarh fresco architectural trail",
      "Discovering the grand cenotaphs of Ramgarh"
    ],
    "region": "West",
    "vibeTags": ["Historic", "Quiet", "Cultural"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 27.9944,
    "longitude": 75.3134,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "mount-abu",
    "name": "Mount Abu",
    "description": "Mount Abu is Rajasthan's only hill station, rising to 1,220 m in the Aravalli Range. It is sacred to both Hindus and Jains — the Dilwara Temples here are considered among the finest examples of Jain marble craftsmanship anywhere in the world.",
    "shortPitch": "Rising high in the Aravalli Range, Mount Abu is Rajasthan's only hill station and a profoundly spiritual sanctuary. It is famed worldwide for the exquisite 11th-century marble carvings of the sacred Dilwara Jain Temples.",
    "topHighlights": [
      "The unparalleled marble carvings of Dilwara Jain Temples",
      "Boating at the scenic Nakki Lake",
      "Sunset viewpoints from Guru Shikhar, Rajasthan's highest peak"
    ],
    "region": "West",
    "vibeTags": ["Peaceful", "Spiritual", "Scenic"],
    "idealSeason": "Sep–Mar",
    "landscapes": ["Royal Cities", "Spiritual India"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3],
    "shoulderMonths": [8, 4],
    "avoidMonths": [5, 6, 7],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 24.5926,
    "longitude": 72.7156,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "mysore",
    "name": "Mysore",
    "description": "Mysore — 'City of Palaces' — is famous for the stunning Mysore Palace, one of India's most visited buildings. It is the cultural capital of Karnataka, home to silk weaving, sandalwood crafts and a living Wadiyar royal tradition. The Dasara festival transforms Mysore into one of India's grandest royal spectacles.",
    "shortPitch": "Known as the 'City of Palaces', Mysore is Karnataka's regal cultural capital celebrated for silk, sandalwood, and a vibrant Wadiyar royal tradition. The spectacularly illuminated Mysore Palace is a breathtaking architectural marvel.",
    "topHighlights": [
      "The stunningly illuminated Mysore Palace",
      "Ascending Chamundi Hill to the Chamundeshwari Temple",
      "Exploring traditional silk and spice stalls at Devaraja Market"
    ],
    "region": "South",
    "vibeTags": ["Regal", "Cultural", "Historic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Royal Cities", "Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 12.2958,
    "longitude": 76.6394,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "rann-of-kutch",
    "name": "Rann of Kutch",
    "description": "The Great Rann of Kutch is one of the world's largest salt deserts — a vast white expanse stretching 7,500 sq km that becomes submerged in monsoon and emerges as a spectral white plain under the full moon in winter. The Rann Utsav festival (Oct–Feb) celebrates the region's tribal crafts, folk music and flamingo colonies.",
    "shortPitch": "The Great Rann of Kutch is a vast, spectral white salt desert stretching endlessly towards the horizon. Emerging in winter, it hosts the vibrant Rann Utsav festival celebrating rich tribal crafts and folk music under a full moon.",
    "topHighlights": [
      "Experiencing the vast White Rann on a full moon night",
      "Attending the cultural Rann Utsav festival",
      "Exploring the ancient Harappan ruins at Dholavira"
    ],
    "region": "West",
    "vibeTags": ["Otherworldly", "Surreal", "Cultural"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Desert"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [4],
    "avoidMonths": [5, 6, 7, 8, 9],
    "closedMonths": [],
    "minRequiredDays": 3,
    "latitude": 23.8322,
    "longitude": 69.8398,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "thar-desert-circuit",
    "name": "Thar Desert Circuit",
    "description": "The Thar Desert — the Great Indian Desert — covers north-western Rajasthan and extends into Pakistan. The circuit through Jaisalmer, Barmer, Khuri and Longewala connects sand dune ecosystems, living villages, war memorials and authentic nomadic camps for an immersive desert experience.",
    "shortPitch": "The Thar Desert circuit provides an immersive journey into the Great Indian Desert's sweeping dune ecosystems. Traversing Jaisalmer, Barmer, and Khuri, it connects living nomadic villages, folk music, and authentic camel safaris.",
    "topHighlights": [
      "Overnight camel safaris and dune camping",
      "Folk textiles and crafts in Barmer",
      "Visiting the historic Longewala War Memorial"
    ],
    "region": "West",
    "vibeTags": ["Wild", "Rustic", "Authentic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Desert"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 5,
    "latitude": 26.9157,
    "longitude": 70.9083,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "alleppey",
    "name": "Alleppey (Alappuzha)",
    "description": "Alleppey — the 'Venice of the East' — is the houseboat capital of India. Its intricate network of canals, lagoons and lakes formed by the Kerala Backwaters is navigated by traditional rice-barge houseboats (kettuvallams), offering one of the most unique and tranquil travel experiences in Asia.",
    "shortPitch": "Often called the 'Venice of the East', Alleppey is the undisputed houseboat capital of India. Cruising its intricate, lush network of canals and lagoons on a traditional rice-barge offers unparalleled tropical tranquility.",
    "topHighlights": [
      "Overnight stays on traditional Kerala houseboats",
      "Navigating the serene backwater canals",
      "Witnessing the spectacular Nehru Trophy Snake Boat Race (August)"
    ],
    "region": "South",
    "vibeTags": ["Dreamy", "Romantic", "Relaxed"],
    "idealSeason": "Sep–Mar",
    "landscapes": ["Backwaters"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3],
    "shoulderMonths": [8, 4],
    "avoidMonths": [5, 6, 7],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 9.4981,
    "longitude": 76.3388,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "kumarakom",
    "name": "Kumarakom",
    "description": "Kumarakom on the shores of Vembanad Lake is Kerala's most luxurious backwater resort destination. The Kumarakom Bird Sanctuary is a haven for migratory birds including Siberian storks, and the village's lagoon-side Ayurveda resorts offer world-class wellness experiences.",
    "shortPitch": "Set majestically on the shores of Vembanad Lake, Kumarakom is Kerala's most luxurious backwater retreat. It is a haven for exotic migratory birds and boasts world-class lagoon-side Ayurveda wellness resorts.",
    "topHighlights": [
      "Luxury wellness resorts and Ayurvedic treatments",
      "Houseboat cruises across Vembanad Lake",
      "Birdwatching at the renowned Kumarakom Bird Sanctuary"
    ],
    "region": "South",
    "vibeTags": ["Luxury", "Peaceful", "Restorative"],
    "idealSeason": "Sep–Mar",
    "landscapes": ["Backwaters", "Wildlife & Jungle"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3],
    "shoulderMonths": [8, 4],
    "avoidMonths": [5, 6, 7],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 9.5828,
    "longitude": 76.4255,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "varanasi",
    "name": "Varanasi",
    "description": "Varanasi is one of the world's oldest continuously inhabited cities and Hinduism's most sacred city. The ghats of the Ganga are a theatre of human existence — morning yoga, boat rides past burning ghats, temple rituals, sadhus and the evening Ganga Aarti fire ceremony make it an overwhelming, unmissable experience.",
    "shortPitch": "As Hinduism's most sacred site, Varanasi is one of the world's oldest and most intense continuously inhabited cities. The ghats of the Ganges River serve as a raw, overwhelming theatre of spiritual existence and ancient ritual.",
    "topHighlights": [
      "The mesmerising evening Ganga Aarti at Dashashwamedh Ghat",
      "Dawn boat rides past ancient riverside ghats",
      "Paying respects at the sacred Kashi Vishwanath Temple"
    ],
    "region": "North",
    "vibeTags": ["Intense", "Sacred", "Spiritual"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 25.3176,
    "longitude": 82.9739,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "haridwar",
    "name": "Haridwar",
    "description": "Haridwar — 'Gateway to God' — is where the Ganges descends from the Himalayas onto the plains, making it one of the seven holiest cities in Hinduism. The evening Ganga Aarti at Har Ki Pauri Ghat, where priests wave fire lamps over the river, is one of India's most moving spiritual spectacles.",
    "shortPitch": "Translating to 'Gateway to God', Haridwar marks the point where the Ganges descends from the Himalayas. It is a profoundly spiritual destination renowned for its evening river rituals and ancient temple traditions.",
    "topHighlights": [
      "The grand evening Ganga Aarti at Har Ki Pauri Ghat",
      "Ropeway trips to the hilltop Mansa Devi Temple",
      "Witnessing the site of the legendary Kumbh Mela"
    ],
    "region": "North",
    "vibeTags": ["Sacred", "Spiritual", "Bustling"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4, 5],
    "avoidMonths": [6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 29.9457,
    "longitude": 78.1642,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "amritsar",
    "name": "Amritsar",
    "description": "Amritsar is the spiritual and cultural capital of Sikhism, home to the Golden Temple (Harmandir Sahib) — the holiest shrine in Sikhism and one of the most visited places in the world. The Jallianwala Bagh massacre memorial and the Wagah Border flag ceremony add profound historical dimensions.",
    "shortPitch": "Amritsar is the vibrant spiritual and cultural capital of Sikhism, universally famed for the radiant Golden Temple. It offers visitors profound historical depth, iconic ceremonies, and legendary Punjabi hospitality.",
    "topHighlights": [
      "The awe-inspiring Golden Temple (Harmandir Sahib)",
      "The deeply moving Jallianwala Bagh Memorial",
      "The electric daily sunset ceremony at the Wagah Border"
    ],
    "region": "North",
    "vibeTags": ["Spiritual", "Cultural", "Historic"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 31.6340,
    "longitude": 74.8723,
    "requiresAcclimatization": false,
    "isHub": true
  },
  {
    "id": "bodh-gaya",
    "name": "Bodh Gaya",
    "description": "Bodh Gaya is the most sacred site in Buddhism — the place where Siddhartha Gautama attained enlightenment under the Bodhi Tree. The Mahabodhi Temple complex (UNESCO World Heritage) attracts Buddhist pilgrims from Tibet, Thailand, Sri Lanka, Japan, and around the world.",
    "shortPitch": "Bodh Gaya is revered globally as the most sacred site in Buddhism, where Siddhartha Gautama achieved enlightenment. The UNESCO-listed temple complex draws monks and pilgrims from across the world into deep, peaceful meditation.",
    "topHighlights": [
      "The magnificent Mahabodhi Temple",
      "Meditating beneath the descendant of the original Bodhi Tree",
      "Exploring international monasteries from Japan, Tibet, and Thailand"
    ],
    "region": "East",
    "vibeTags": ["Sacred", "Peaceful", "Spiritual"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 24.6961,
    "longitude": 84.9869,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "tirupati",
    "name": "Tirupati",
    "description": "The Tirumala Venkateswara Temple at Tirupati is the richest and most visited place of worship in the world, receiving 50,000–100,000 pilgrims daily. The main deity, Lord Venkateswara, is believed to grant all wishes, and the tradition of tonsuring (head shaving) as an offering is observed by millions.",
    "shortPitch": "Tirupati is home to the Tirumala Venkateswara Temple, renowned as the richest and most visited place of worship in the world. Ascending its sacred hills is an intense, awe-inspiring display of unwavering faith and devotion.",
    "topHighlights": [
      "Darshan at the majestic Tirumala Venkateswara Temple",
      "Historic visits to the nearby Chandragiri Fort",
      "The beautiful cascading waters of Kapila Theertham"
    ],
    "region": "South",
    "vibeTags": ["Sacred", "Bustling", "Spiritual"],
    "idealSeason": "Sep–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [9, 10, 11, 12, 1, 2, 3],
    "shoulderMonths": [8, 4],
    "avoidMonths": [5, 6, 7],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 13.6288,
    "longitude": 79.4192,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "puri",
    "name": "Puri",
    "description": "Puri is one of Hinduism's four sacred Dhams and home to the Jagannath Temple — one of India's most important shrines. The annual Rath Yatra chariot festival draws millions and is the world's largest chariot procession. The adjacent beach is one of Odisha's most popular seaside resorts.",
    "shortPitch": "Puri is an ancient coastal Dham deeply revered for the monumental Jagannath Temple. Alongside its vibrant spiritual rituals and the massive annual Rath Yatra, it offers expansive sandy beaches along the Bay of Bengal.",
    "topHighlights": [
      "The highly sacred Jagannath Temple",
      "Witnessing the colossal Rath Yatra Chariot Festival",
      "Relaxing at the popular Puri Beach"
    ],
    "region": "East",
    "vibeTags": ["Sacred", "Vibrant", "Spiritual"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India", "Beaches"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 19.8135,
    "longitude": 85.8312,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "ajmer",
    "name": "Ajmer",
    "description": "Ajmer's Dargah Sharif — the shrine of Sufi saint Khwaja Moinuddin Chishti — is among the most important Muslim pilgrimage sites in South Asia, drawing devotees of all faiths. Just 11 km away, Pushkar is one of Hinduism's holiest sites, creating an extraordinary interfaith corridor.",
    "shortPitch": "Set in the Aravalli mountains, Ajmer is a deeply historic city and home to the universally revered Dargah Sharif shrine. Its beautiful lakes and Sufi heritage create a profound sense of interfaith devotion.",
    "topHighlights": [
      "The sacred Dargah Sharif of Khwaja Moinuddin Chishti",
      "Live Qawwali music performances at the dargah",
      "Relaxing by the shores of Ana Sagar Lake"
    ],
    "region": "West",
    "vibeTags": ["Sacred", "Cultural", "Spiritual"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 1,
    "latitude": 26.4499,
    "longitude": 74.6399,
    "requiresAcclimatization": false,
    "isHub": false
  },
  {
    "id": "shirdi",
    "name": "Shirdi",
    "description": "Shirdi is home to the Sai Baba Samadhi Mandir — one of the wealthiest temples in India and the most visited destination in Maharashtra. Millions of devotees from all religions visit annually to pay homage to Sai Baba, a saint revered by Hindus, Muslims and people of all faiths.",
    "shortPitch": "Shirdi is the sacred spiritual home of the widely revered saint Sai Baba. Drawing millions of devotees from every faith, the serene temple complex offers a deeply peaceful atmosphere centered around universal devotion.",
    "topHighlights": [
      "Darshan at the main Sai Baba Samadhi Mandir",
      "Visiting the historic Dwarkamai Mosque",
      "Strolling through the peaceful Lendi Baugh garden"
    ],
    "region": "West",
    "vibeTags": ["Sacred", "Spiritual", "Peaceful"],
    "idealSeason": "Oct–Mar",
    "landscapes": ["Spiritual India"],
    "peakMonths": [10, 11, 12, 1, 2, 3],
    "shoulderMonths": [9, 4],
    "avoidMonths": [5, 6, 7, 8],
    "closedMonths": [],
    "minRequiredDays": 2,
    "latitude": 19.7645,
    "longitude": 74.4762,
    "requiresAcclimatization": false,
    "isHub": false
  }
];

data.push(...batch3);
fs.writeFileSync('prisma/data.json', JSON.stringify(data, null, 2));
console.log('Appended batch 3.');
